variable "subscription_id" {
  description = "Azure subscription ID. If null, the ARM_SUBSCRIPTION_ID environment variable is used."
  type        = string
  default     = null
}

variable "project_name" {
  description = "Base name used to derive resource names."
  type        = string
  default     = "edit30"

  validation {
    condition     = can(regex("^[a-z0-9]{2,12}$", var.project_name))
    error_message = "project_name must be 2-12 lowercase letters/digits (it is used in the storage account name, which is limited to 24 characters)."
  }
}

variable "environment" {
  description = "Environment name, e.g. dev, test or prod."
  type        = string
  default     = "dev"

  validation {
    condition     = can(regex("^[a-z0-9]{2,6}$", var.environment))
    error_message = "environment must be 2-6 lowercase letters/digits."
  }
}

variable "location" {
  description = "Azure region for the resource group, App Service and storage account."
  type        = string
  default     = "westeurope"
}

variable "static_web_app_location" {
  description = "Region for the Static Web App. Only a few regions are supported: westus2, centralus, eastus2, westeurope, eastasia."
  type        = string
  default     = "westeurope"

  validation {
    condition     = contains(["westus2", "centralus", "eastus2", "westeurope", "eastasia"], var.static_web_app_location)
    error_message = "Static Web Apps are only available in westus2, centralus, eastus2, westeurope and eastasia."
  }
}

variable "static_web_app_sku" {
  description = "Static Web App SKU: Free or Standard."
  type        = string
  default     = "Free"

  validation {
    condition     = contains(["Free", "Standard"], var.static_web_app_sku)
    error_message = "static_web_app_sku must be Free or Standard."
  }
}

variable "app_service_sku" {
  description = "App Service plan SKU for the backend (e.g. B1, B2, S1, P1v3). Matches the B1 used in edit30backend/azure/main.bicep."
  type        = string
  default     = "B1"
}

variable "node_version" {
  description = "Node.js runtime for the backend App Service."
  type        = string
  default     = "20-lts"
}

variable "sql_database_name" {
  description = "Name of the Azure SQL database."
  type        = string
  default     = "edit30app"
}

variable "sql_admin_login" {
  description = "Administrator login of the SQL server. The password is generated by Terraform."
  type        = string
  default     = "edit30admin"
}

variable "sql_free_limit_exhaustion_behavior" {
  description = "What happens when the monthly free allowance (100,000 vCore-seconds) is used up: AutoPause (database pauses until next month, never billed) or BillOverUsage (keeps running and is billed). Defaults to BillOverUsage because sql_auto_pause_delay_minutes below disables idle auto-pause too — with AutoPause, the database would still pause once the free allowance ran out, undoing that."
  type        = string
  default     = "BillOverUsage"

  validation {
    condition     = contains(["AutoPause", "BillOverUsage"], var.sql_free_limit_exhaustion_behavior)
    error_message = "sql_free_limit_exhaustion_behavior must be AutoPause or BillOverUsage."
  }
}

variable "sql_min_capacity" {
  description = "Minimum serverless vCores the database scales down to. Above the free tier's covered baseline, running time is billed at this rate whenever idle, so raising it trades a bit of always-on cost for never fully pausing."
  type        = number
  default     = 1
}

variable "sql_auto_pause_delay_minutes" {
  description = "Idle minutes before the database auto-pauses (causing a slow cold-start on the next request), or -1 to disable auto-pause entirely and stay always-on."
  type        = number
  default     = -1
}

variable "sql_client_ip_addresses" {
  description = "Public IPv4 addresses allowed to connect to the SQL server directly (e.g. your own, to inspect data). Azure services, including the backend App Service, are always allowed."
  type        = list(string)
  default     = []
}

variable "additional_cors_origins" {
  description = "Extra origins the backend should accept, e.g. [\"http://localhost:3000\"] for local development. The Static Web App origin is always allowed."
  type        = list(string)
  default     = []
}

variable "storage_containers" {
  description = "Names of private blob containers to create in the storage account."
  type        = list(string)
  default     = ["uploads"]
}

variable "storage_replication_type" {
  description = "Storage account replication: LRS, GRS, ZRS, etc."
  type        = string
  default     = "LRS"
}

variable "tags" {
  description = "Extra tags applied to all resources."
  type        = map(string)
  default     = {}
}
